version: 0.2

services:
  web: 
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - '8000:8000'
artifacts:
  files:
    - '**/*'
  name: $AWS_REGION-$(date +%Y-%m-%d) 
